const PHOTO_LIBRARY = [
  { "id": "pin01", "title": "Architecture Design 01", "cat": "Architecture", "type": "image", "src": "./assets/pin01.png", "desc": "Minimalist urban structure." },
  { "id": "pin02", "title": "Architecture Design 02", "cat": "Architecture", "type": "image", "src": "./assets/pin02.png", "desc": "Glass and steel symmetry." },
  { "id": "pin03", "title": "Architecture Design 03", "cat": "Architecture", "type": "video", "src": "./assets/pin03_thumb.png", "vid": "./assets/pin03_video.mp4", "desc": "Urban timelapse." },
  { "id": "pin04", "title": "Architecture Design 04", "cat": "Architecture", "type": "image", "src": "./assets/pin04.png", "desc": "Brutalist concrete texture." },
  { "id": "pin05", "title": "Architecture Design 05", "cat": "Architecture", "type": "image", "src": "./assets/pin05.png", "desc": "Classic European arches." },
  { "id": "pin06", "title": "Architecture Design 06", "cat": "Architecture", "type": "image", "src": "./assets/pin06.png", "desc": "Interior wooden stairs." },
  { "id": "pin07", "title": "Architecture Design 07", "cat": "Architecture", "type": "image", "src": "./assets/pin07.png", "desc": "Futuristic skyscraper." },
  { "id": "pin09", "title": "Architecture Design 09", "cat": "Architecture", "type": "image", "src": "./assets/pin09.png", "desc": "Rustic brick wall." },
  { "id": "pin10", "title": "Architecture Design 10", "cat": "Architecture", "type": "image", "src": "./assets/pin10.png", "desc": "Sustainable green roof." },
  { "id": "pin11", "title": "Nature Exploration 11", "cat": "Nature", "type": "image", "src": "./assets/pin11.png", "desc": "Misty mountain peaks." },
  { "id": "pin12", "title": "Nature Exploration 12", "cat": "Nature", "type": "image", "src": "./assets/pin12.png", "desc": "Deep forest trail." },
  { "id": "pin13", "title": "Nature Exploration 13", "cat": "Nature", "type": "video", "src": "./assets/pin13_thumb.png", "vid": "./assets/pin13_video.mp4", "desc": "Ocean wave motion." },
  { "id": "pin14", "title": "Nature Exploration 14", "cat": "Nature", "type": "image", "src": "./assets/pin14.png", "desc": "Desert sand dunes." },
  { "id": "pin15", "title": "Nature Exploration 15", "cat": "Nature", "type": "image", "src": "./assets/pin15.png", "desc": "Autumn leaf colors." },
  { "id": "pin16", "title": "Nature Exploration 16", "cat": "Nature", "type": "image", "src": "./assets/pin16.png", "desc": "Crystal clear lake." },
  { "id": "pin17", "title": "Nature Exploration 17", "cat": "Nature", "type": "image", "src": "./assets/pin17.png", "desc": "Blooming spring flowers." },
  { "id": "pin18", "title": "Nature Exploration 18", "cat": "Nature", "type": "image", "src": "./assets/pin18.png", "desc": "Snowy winter forest." },
  { "id": "pin19", "title": "Nature Exploration 19", "cat": "Nature", "type": "image", "src": "./assets/pin19.png", "desc": "Starry night sky." },
  { "id": "pin20", "title": "Nature Exploration 20", "cat": "Nature", "type": "image", "src": "./assets/pin20.png", "desc": "Golden sunset horizon." },
  { "id": "pin21", "title": "Art Inspiration 21", "cat": "Art", "type": "image", "src": "./assets/pin21.png", "desc": "Creative abstract oil painting." },
  { "id": "pin22", "title": "Art Inspiration 22", "cat": "Art", "type": "image", "src": "./assets/pin22.png", "desc": "Modern digital sculpture." },
  { "id": "pin23", "title": "Art Inspiration 23", "cat": "Art", "type": "image", "src": "./assets/pin23.png", "desc": "Vibrant pop art colors." },
  { "id": "pin24", "title": "Art Inspiration 24", "cat": "Art", "type": "image", "src": "./assets/pin24.png", "desc": "Minimalist pencil sketch." },
  { "id": "pin25", "title": "Art Inspiration 25", "cat": "Art", "type": "image", "src": "./assets/pin25.png", "desc": "Graffiti street art mural." },
  { "id": "pin26", "title": "Art Inspiration 26", "cat": "Art", "type": "image", "src": "./assets/pin26.png", "desc": "Classical marble statue detail." },
  { "id": "pin27", "title": "Art Inspiration 27", "cat": "Art", "type": "image", "src": "./assets/pin27.png", "desc": "Surrealist watercolor dreamscape." },
  { "id": "pin28", "title": "Art Inspiration 28", "cat": "Art", "type": "video", "src": "./assets/pin28_thumb.png", "vid": "./assets/pin28_video.mp4", "desc": "Fluid ink in water animation." },
  { "id": "pin29", "title": "Art Inspiration 29", "cat": "Art", "type": "image", "src": "./assets/pin29.png", "desc": "Geometric pattern illustration." },
  { "id": "pin30", "title": "Art Inspiration 30", "cat": "Art", "type": "image", "src": "./assets/pin30.png", "desc": "Conceptual photography project." },
  { "id": "pin31", "title": "Travel Adventure 31", "cat": "Travel", "type": "image", "src": "./assets/pin31.jpg", "desc": "Hidden alleyway in Kyoto." },
  { "id": "pin32", "title": "Travel Adventure 32", "cat": "Travel", "type": "image", "src": "./assets/pin32.jpg", "desc": "Sunset over Santorini cliffs." },
  { "id": "pin33", "title": "Travel Adventure 33", "cat": "Travel", "type": "image", "src": "./assets/pin33.jpg", "desc": "Busy markets of Marrakesh." },
  { "id": "pin34", "title": "Travel Adventure 34", "cat": "Travel", "type": "image", "src": "./assets/pin34.jpg", "desc": "Icebergs in an Icelandic lagoon." },
  { "id": "pin35", "title": "Travel Adventure 35", "cat": "Travel", "type": "image", "src": "./assets/pin35.jpg", "desc": "Ancient ruins in Machu Picchu." },
  { "id": "pin36", "title": "Travel Adventure 36", "cat": "Travel", "type": "image", "src": "./assets/pin36.jpg", "desc": "City skyline of New York at dusk." },
  { "id": "pin37", "title": "Travel Adventure 37", "cat": "Travel", "type": "image", "src": "./assets/pin37.jpg", "desc": "Pristine beaches of the Maldives." },
  { "id": "pin38", "title": "Travel Adventure 38", "cat": "Travel", "type": "image", "src": "./assets/pin38.jpg", "desc": "Camping under the Northern Lights." },
  { "id": "pin39", "title": "Travel Adventure 39", "cat": "Travel", "type": "image", "src": "./assets/pin39.jpg", "desc": "Hot air balloons over Cappadocia." },
  { "id": "pin40", "title": "Travel Adventure 40", "cat": "Travel", "type": "image", "src": "./assets/pin40.jpg", "desc": "Historic canal houses in Amsterdam." },
  { "id": "pin41", "title": "Lifestyle Trends 41", "cat": "Lifestyle", "type": "image", "src": "./assets/pin41.jpg", "desc": "Minimalist home office setup." },
  { "id": "pin42", "title": "Lifestyle Trends 42", "cat": "Lifestyle", "type": "image", "src": "./assets/pin42.jpg", "desc": "Morning coffee by the window." },
  { "id": "pin43", "title": "Lifestyle Trends 43", "cat": "Lifestyle", "type": "video", "src": "./assets/pin43_thumb.jpg", "vid": "./assets/pin43_video.mp4", "desc": "Healthy vegan meal prep." },
  { "id": "pin44", "title": "Lifestyle Trends 44", "cat": "Lifestyle", "type": "image", "src": "./assets/pin44.jpg", "desc": "Urban gardening on a balcony." },
  { "id": "pin45", "title": "Lifestyle Trends 45", "cat": "Lifestyle", "type": "image", "src": "./assets/pin45.jpg", "desc": "Sustainable fashion choices." },
  { "id": "pin46", "title": "Lifestyle Trends 46", "cat": "Lifestyle", "type": "image", "src": "./assets/pin46.jpg", "desc": "Evening yoga at home." },
  { "id": "pin47", "title": "Lifestyle Trends 47", "cat": "Lifestyle", "type": "image", "src": "./assets/pin47.jpg", "desc": "Cozy reading nook essentials." },
  { "id": "pin48", "title": "Lifestyle Trends 48", "cat": "Lifestyle", "type": "image", "src": "./assets/pin48.jpg", "desc": "Skincare routine flatlay." },
  { "id": "pin49", "title": "Lifestyle Trends 49", "cat": "Lifestyle", "type": "image", "src": "./assets/pin49.jpg", "desc": "Minimalist wardrobe organization." },
  { "id": "pin50", "title": "Lifestyle Trends 50", "cat": "Lifestyle", "type": "image", "src": "./assets/pin50.jpg", "desc": "Baking fresh sourdough bread." },
  { "id": "pin51", "title": "Fashion Style 51", "cat": "Fashion", "type": "image", "src": "./assets/pin51.jpg", "desc": "Vintage 90s aesthetic outfit." },
  { "id": "pin52", "title": "Fashion Style 52", "cat": "Fashion", "type": "image", "src": "./assets/pin52.jpg", "desc": "High fashion runway detail." },
  { "id": "pin53", "title": "Fashion Style 53", "cat": "Fashion", "type": "image", "src": "./assets/pin53.jpg", "desc": "Streetwear layering guide." },
  { "id": "pin54", "title": "Fashion Style 54", "cat": "Fashion", "type": "image", "src": "./assets/pin54.jpg", "desc": "Luxury watch collection." },
  { "id": "pin55", "title": "Fashion Style 55", "cat": "Fashion", "type": "image", "src": "./assets/pin55.jpg", "desc": "Pastel color palette outfit." },
  { "id": "pin56", "title": "Fashion Style 56", "cat": "Fashion", "type": "image", "src": "./assets/pin56.jpg", "desc": "Classic denim on denim." },
  { "id": "pin57", "title": "Fashion Style 57", "cat": "Fashion", "type": "image", "src": "./assets/pin57.jpg", "desc": "Minimalist jewelry styling." },
  { "id": "pin58", "title": "Fashion Style 58", "cat": "Fashion", "type": "video", "src": "./assets/pin58_thumb.jpg", "vid": "./assets/pin58_video.mp4", "desc": "Sneaker unboxing video." },
  { "id": "pin59", "title": "Fashion Style 59", "cat": "Fashion", "type": "image", "src": "./assets/pin59.jpg", "desc": "Sustainable linen summer dress." },
  { "id": "pin60", "title": "Fashion Style 60", "cat": "Fashion", "type": "image", "src": "./assets/pin60.jpg", "desc": "Monochrome business casual." },
  { "id": "pin61", "title": "Architecture Design 61", "cat": "Architecture", "type": "image", "src": "./assets/pin61.jpg", "desc": "Curved glass facade." },
  { "id": "pin62", "title": "Architecture Design 62", "cat": "Architecture", "type": "image", "src": "./assets/pin62.jpg", "desc": "Gothic cathedral window." },
  { "id": "pin63", "title": "Architecture Design 63", "cat": "Architecture", "type": "image", "src": "./assets/pin63.jpg", "desc": "Modern bamboo structure." },
  { "id": "pin64", "title": "Architecture Design 64", "cat": "Architecture", "type": "image", "src": "./assets/pin64.jpg", "desc": "Industrial loft interior." },
  { "id": "pin65", "title": "Nature Exploration 65", "cat": "Nature", "type": "image", "src": "./assets/pin65.jpg", "desc": "Macro dew drop on petal." },
  { "id": "pin66", "title": "Nature Exploration 66", "cat": "Nature", "type": "image", "src": "./assets/pin66.jpg", "desc": "Desert oasis at sunset." },
  { "id": "pin67", "title": "Nature Exploration 67", "cat": "Nature", "type": "image", "src": "./assets/pin67.jpg", "desc": "Tropical rainforest canopy." },
  { "id": "pin68", "title": "Nature Exploration 68", "cat": "Nature", "type": "image", "src": "./assets/pin68.jpg", "desc": "Lush green rolling hills." },
  { "id": "pin69", "title": "Art Inspiration 69", "cat": "Art", "type": "image", "src": "./assets/pin69.jpg", "desc": "Charcoal portrait study." },
  { "id": "pin70", "title": "Art Inspiration 70", "cat": "Art", "type": "image", "src": "./assets/pin70.jpg", "desc": "Contemporary art installation." },
  { "id": "pin71", "title": "Travel Adventure 71", "cat": "Travel", "type": "image", "src": "./assets/pin71.jpg", "desc": "Mountain cabin in Switzerland." },
  { "id": "pin72", "title": "Travel Adventure 72", "cat": "Travel", "type": "image", "src": "./assets/pin72.jpg", "desc": "Lavender fields in Provence." },
  { "id": "pin73", "title": "Travel Adventure 73", "cat": "Travel", "type": "video", "src": "./assets/pin73_thumb.jpg", "vid": "./assets/pin73_video.mp4", "desc": "Tokyo neon night walk." },
  { "id": "pin74", "title": "Travel Adventure 74", "cat": "Travel", "type": "image", "src": "./assets/pin74.jpg", "desc": "Red rock formations in Sedona." },
  { "id": "pin75", "title": "Lifestyle Trends 75", "cat": "Lifestyle", "type": "image", "src": "./assets/pin75.jpg", "desc": "Artisan pottery workshop." },
  { "id": "pin76", "title": "Lifestyle Trends 76", "cat": "Lifestyle", "type": "image", "src": "./assets/pin76.jpg", "desc": "Home library wall goals." },
  { "id": "pin77", "title": "Lifestyle Trends 77", "cat": "Lifestyle", "type": "image", "src": "./assets/pin77.jpg", "desc": "Picnic in the park setup." },
  { "id": "pin78", "title": "Lifestyle Trends 78", "cat": "Lifestyle", "type": "image", "src": "./assets/pin78.jpg", "desc": "Candle making hobby kit." },
  { "id": "pin79", "title": "Fashion Style 79", "cat": "Fashion", "type": "image", "src": "./assets/pin79.jpg", "desc": "Street photography outfit." },
  { "id": "pin80", "title": "Fashion Style 80", "cat": "Fashion", "type": "image", "src": "./assets/pin80.jpg", "desc": "Retro sunglasses collection." },
  { "id": "pin81", "title": "Architecture Design 81", "cat": "Architecture", "type": "image", "src": "./assets/pin81.jpg", "desc": "Spiral staircase top view." },
  { "id": "pin82", "title": "Architecture Design 82", "cat": "Architecture", "type": "image", "src": "./assets/pin82.jpg", "desc": "Mediterranean white villa." },
  { "id": "pin83", "title": "Nature Exploration 83", "cat": "Nature", "type": "image", "src": "./assets/pin83.jpg", "desc": "Aerial reef view." },
  { "id": "pin84", "title": "Nature Exploration 84", "cat": "Nature", "type": "image", "src": "./assets/pin84.jpg", "desc": "Giant redwood forest." },
  { "id": "pin85", "title": "Art Inspiration 85", "cat": "Art", "type": "image", "src": "./assets/pin85.jpg", "desc": "Glitch art digital edit." },
  { "id": "pin86", "title": "Art Inspiration 86", "cat": "Art", "type": "image", "src": "./assets/pin86.jpg", "desc": "Origami paper animals." },
  { "id": "pin87", "title": "Travel Adventure 87", "cat": "Travel", "type": "image", "src": "./assets/pin87.jpg", "desc": "Venice gondola ride." },
  { "id": "pin88", "title": "Fashion Style 88", "cat": "Fashion", "type": "image", "src": "./assets/pin88.jpg", "desc": "Minimalist winter coat." }
];

